# Generated by Django 5.0.2 on 2024-02-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduSysApp', '0003_remove_user_role_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='StudyGroup',
        ),
    ]
