# Generated by Django 5.0.2 on 2024-02-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduSysApp', '0004_rename_group_studygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
