# Generated by Django 5.0.2 on 2024-02-20 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduSysApp', '0006_studygroup_course_alter_course_course_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='employee',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='EduSysApp.employee', verbose_name='Сотрудник'),
        ),
    ]
