# Generated by Django 5.0.2 on 2024-02-20 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduSysApp', '0007_grade_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Значение оценки'),
        ),
    ]
