# Generated by Django 5.0.2 on 2024-02-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduSysApp', '0009_alter_grade_employee_alter_request_lesson_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
