# Generated by Django 5.0.2 on 2024-02-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduSysApp', '0010_delete_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
