# Generated by Django 5.0.2 on 2024-02-20 17:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduSysApp', '0011_delete_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Значение оценки')),
                ('grade_date', models.DateField(verbose_name='Дата выставления оценки')),
                ('employee', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='EduSysApp.employee', verbose_name='Сотрудник')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduSysApp.student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduSysApp.subject', verbose_name='Предмет')),
            ],
        ),
    ]
