# Generated by Django 5.0.2 on 2024-02-20 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduSysApp', '0012_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_status', models.BooleanField(default=True, verbose_name='Статус занятия')),
                ('request_status', models.BooleanField(default=False, verbose_name='Статус запроса')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduSysApp.employee', verbose_name='Сотрудник')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduSysApp.lesson', verbose_name='Урок')),
            ],
        ),
    ]
