# Generated by Django 5.0.2 on 2024-02-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduSysApp', '0014_remove_request_employee_request_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user',
            new_name='employee',
        ),
    ]
