# Generated by Django 5.0.2 on 2024-02-21 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduSysApp', '0015_rename_user_request_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EduSysApp.employee', verbose_name='Сотрудник'),
        ),
    ]
